[package]
name = "peas"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
fastrand = "2.1.0"
rayon = "1.10.0"
wasm-encoder = { version = "0.207.0", features = ["wasmparser"] }
wasmparser = "0.207.0"
