[package]
name = "peas"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
eyre = "0.6.12"
log = "0.4.21"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
rayon = "1.10.0"
walrus = { version = "0.20.3", features = ["parallel"] }
wasm-encoder = { version = "0.209.1", features = ["wasmparser"] }
wasmparser = "0.209.1"
wasmtime = "21.0.1"
