[project]
name = "peas"
version = "0.1.0"
description = "Additional scripts for PEAS"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.9.3",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
]
